default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: elevate_development
  queue:
    <<: *default
    database: elevate_development_queue

test:
  <<: *default
  database: elevate_test
  queue:
    <<: *default
    database: elevate_test_queue

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
  queue:
    <<: *default
    url: <%= ENV['QUEUE_DATABASE_URL'] || ENV['DATABASE_URL'] %>
